# Generated by Django 3.1 on 2020-08-29 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Invalid', 'Invalid'), ('Done', 'Done')], default='New', max_length=11)),
            ],
        ),
    ]
